name: chat_group
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  bubble: ^1.2.1
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  firebase_storage: ^11.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_conditional_rendering: ^2.0.0
  fluttericon: ^2.0.0
  fluttertoast: ^8.1.1
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
    - family: SocialMedia
      fonts:
        - asset: assets/icons/google.ttf
